name: cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cache_cleanup:
    runs-on: ubuntu-latest
    env:
      BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
    permissions:
      actions: write
    steps:
      - uses: actions/github-script@v6
        name: Cleanup caches for closed PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            echo "Fetching list of cache keys"
            cacheKeysForPR=$(gh cache list --ref $BRANCH --limit 100 --json id --jq '.[].id')

            ## Setting this to not fail the workflow while deleting cache keys.
            set +e
            echo "Deleting caches..."
            for cacheKey in $cacheKeysForPR
            do
                gh cache delete $cacheKey
            done
            echo "Done"
            set -e
